# Generated by Django 4.0.5 on 2022-07-08 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('designation_en', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=30)),
                ('fy_np', models.CharField(max_length=30)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('fy', 'fy_np', 'isactive')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=200)),
                ('officeAddress', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_en', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_description', models.CharField(max_length=40)),
                ('type_description_en', models.CharField(max_length=40)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YojanaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_ref', models.CharField(max_length=40)),
                ('prj_name', models.CharField(max_length=100)),
                ('prj_tole', models.CharField(max_length=50)),
                ('affected_people', models.IntegerField()),
                ('prj_duration', models.FloatField()),
                ('prj_estimate', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('fy_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.fy')),
                ('prj_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.projecttype')),
                ('type_prj_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.typeofproject')),
            ],
        ),
        migrations.CreateModel(
            name='relmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offRef', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.office')),
                ('uRef', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanketNo', models.CharField(blank=True, max_length=30)),
                ('contactNo', models.CharField(blank=True, max_length=13)),
                ('is_active', models.BooleanField(default=False)),
                ('offref', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='plan.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson_name', models.CharField(max_length=50)),
                ('chairperson_citizen', models.CharField(max_length=50)),
                ('memberone_name', models.CharField(max_length=50)),
                ('memberone_citizen', models.CharField(max_length=50)),
                ('memberone_citizen_img', models.ImageField(default='default.jpg', upload_to='path')),
                ('memberone_image', models.ImageField(default='default.jpg', upload_to='path')),
                ('membertwo_name', models.CharField(max_length=50)),
                ('membertwo_citizen', models.CharField(max_length=50)),
                ('membertwo_citizen_img', models.ImageField(default='default.jpg', upload_to='path')),
                ('membertwo_image', models.ImageField(default='default.jpg', upload_to='path')),
                ('memberthree_name', models.CharField(max_length=50)),
                ('memberthree_citizen', models.CharField(max_length=50)),
                ('memberthree_citizen_img', models.ImageField(default='default.jpg', upload_to='path')),
                ('memberthree_image', models.ImageField(default='default.jpg', upload_to='path')),
                ('project_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.yojanadetails')),
            ],
        ),
    ]
