# Generated by Django 4.0.5 on 2022-07-11 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_community',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_community_en',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_household',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_household_en',
            field=models.CharField(default='0', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_people_en',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_comittee',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_gai_sasa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_gai_sasa_en',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_palika',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_palika_en',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='prj_estimate_en',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='affected_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 18, 21, 989794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 18, 21, 989794, tzinfo=utc)),
        ),
    ]
