# Generated by Django 4.0.5 on 2022-07-09 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yojanadetails',
            name='sector_ref',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='plan.majorsector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 21, 24, 455105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 21, 24, 455105, tzinfo=utc)),
        ),
    ]
