# Generated by Django 4.0.5 on 2022-07-24 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 4, 6, 8, 831759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 24, 4, 6, 8, 831759, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('budget_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.budgettype')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.yojanatype')),
            ],
        ),
    ]
