# Generated by Django 4.0.5 on 2022-07-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='type_ref',
        ),
        migrations.RemoveField(
            model_name='typeofproject',
            name='project_type_ref',
        ),
        migrations.RemoveField(
            model_name='unitofwork',
            name='unit_ref',
        ),
    ]
