# Generated by Django 4.0.5 on 2022-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='type_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofproject',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typeofproject',
            name='type_description_en',
            field=models.CharField(default='Null', max_length=40),
            preserve_default=False,
        ),
    ]
