# Generated by Django 4.0.5 on 2022-07-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='offref',
            new_name='org_ref',
        ),
    ]
