# Generated by Django 4.0.5 on 2022-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type_ref', models.IntegerField()),
                ('type_description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ref', models.IntegerField()),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='memberone_citizen_img',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='committee',
            name='memberone_image',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='committee',
            name='memberthree_citizen_img',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='committee',
            name='memberthree_image',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='committee',
            name='membertwo_citizen_img',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='committee',
            name='membertwo_image',
            field=models.ImageField(default='default.jpg', upload_to='path'),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='prj_tole',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
