# Generated by Django 4.0.5 on 2022-06-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_designation_office_relmap_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=30)),
                ('fy_np', models.CharField(max_length=30)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('fy', 'fy_np', 'isactive')},
            },
        ),
    ]
