# Generated by Django 4.0.5 on 2022-07-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_rename_offref_profile_org_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='org_ref',
        ),
    ]
