# Generated by Django 4.0.5 on 2022-07-09 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_yojanadetails_sector_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yojanadetails',
            name='estimate_in_letters',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 36, 9, 343146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 36, 9, 343146, tzinfo=utc)),
        ),
    ]
