# Generated by Django 4.0.5 on 2022-07-11 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_yojanadetails_affected_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yojanadetails',
            name='amt_from_comittee_en',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='amt_from_comittee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 34, 24, 935589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 34, 24, 935589, tzinfo=utc)),
        ),
    ]
