# Generated by Django 4.0.5 on 2022-06-29 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='yojanadetails',
            name='affected_people',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='type_prj_ref',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.RESTRICT, to='plan.typeofproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.projecttype'),
        ),
    ]
