# Generated by Django 4.0.5 on 2022-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_profile_org_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_body', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
