# Generated by Django 4.0.5 on 2022-07-23 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_yojanadetails_prj_completion_date_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 13, 54, 32, 898971, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 13, 54, 32, 898971, tzinfo=utc)),
        ),
    ]
