# Generated by Django 4.0.5 on 2022-07-11 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_yojanadetails_amt_from_comittee_np_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 41, 6, 913557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 10, 41, 6, 913557, tzinfo=utc)),
        ),
    ]
