# Generated by Django 4.0.5 on 2022-07-09 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_comittee_project_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comitteemembers',
            name='chairperson_citizen',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='chairperson_name',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='memberthree_citizen',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='memberthree_citizen_img',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='memberthree_image',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='memberthree_name',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='membertwo_citizen',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='membertwo_citizen_img',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='membertwo_image',
        ),
        migrations.RemoveField(
            model_name='comitteemembers',
            name='membertwo_name',
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 1, 13, 312680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 1, 13, 312680, tzinfo=utc)),
        ),
    ]
