# Generated by Django 4.0.5 on 2022-07-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_doc_doc_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_ref',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofwork',
            name='unit_name_en',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('count_np', models.CharField(max_length=10)),
                ('fy_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.fy')),
            ],
        ),
    ]
