# Generated by Django 4.0.5 on 2022-07-09 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_remove_comitteemembers_chairperson_citizen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comitteemembers',
            old_name='memberone_citizen',
            new_name='member_citizen',
        ),
        migrations.RenameField(
            model_name='comitteemembers',
            old_name='memberone_citizen_img',
            new_name='member_citizen_img',
        ),
        migrations.RenameField(
            model_name='comitteemembers',
            old_name='memberone_image',
            new_name='member_image',
        ),
        migrations.RenameField(
            model_name='comitteemembers',
            old_name='memberone_name',
            new_name='member_name',
        ),
        migrations.AddField(
            model_name='comitteemembers',
            name='member_designation',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='plan.designation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 2, 25, 151543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 2, 25, 151543, tzinfo=utc)),
        ),
    ]
