# Generated by Django 4.0.5 on 2022-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_doc_doc_ref_unitofwork_unit_name_en_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comittee_name', models.CharField(max_length=200)),
                ('comittee_name_en', models.CharField(max_length=200)),
                ('comittee_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=100)),
                ('group_type_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='committee',
            new_name='ComitteeMembers',
        ),
    ]
