# Generated by Django 4.0.5 on 2022-07-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_comittee_responsiblegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitteemembers',
            name='comittee_ref',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='plan.comittee'),
            preserve_default=False,
        ),
    ]
