# Generated by Django 4.0.5 on 2022-07-10 02:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_yojanadetails_prj_completion_date_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 2, 46, 30, 676807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 2, 46, 30, 676807, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProgressGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('amt', models.FloatField()),
                ('remarks', models.TextField(max_length=200)),
                ('sector_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.majorsector')),
            ],
        ),
    ]
