# Generated by Django 4.0.5 on 2022-07-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_comitteemembers_comittee_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='comittee',
            name='black_listed',
            field=models.BooleanField(default=False),
        ),
    ]
