# Generated by Django 4.0.5 on 2022-07-10 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_yojanadetails_prj_completion_date_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitteemembers',
            name='member_phone',
            field=models.CharField(default='0', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karyadesh',
            name='title',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samjhauta',
            name='title',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tippani',
            name='title',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 6, 49, 16, 968350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 6, 49, 16, 968350, tzinfo=utc)),
        ),
    ]
