# Generated by Django 4.0.5 on 2022-07-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_comittee_black_listed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woda', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='yojanadetails',
            name='area_ref',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='plan.woda'),
            preserve_default=False,
        ),
    ]
