# Generated by Django 4.0.5 on 2022-07-10 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_comitteemembers_member_phone_karyadesh_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 8, 31, 46, 473245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 8, 31, 46, 473245, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='FinalizeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField(default=datetime.datetime(2022, 7, 10, 8, 31, 46, 481245, tzinfo=utc))),
                ('prj_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plan.yojanadetails')),
            ],
        ),
    ]
