# Generated by Django 4.0.5 on 2022-07-09 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_remove_yojanadetails_prj_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 18, 31, 118796)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 18, 31, 118796)),
        ),
    ]
