# Generated by Django 4.0.5 on 2022-07-10 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_finalize_alter_yojanadetails_prj_completion_date_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalize',
            name='message',
            field=models.TextField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalize',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 8, 51, 48, 826507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 8, 51, 48, 826507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 10, 8, 51, 48, 826507, tzinfo=utc)),
        ),
    ]
