# Generated by Django 4.0.5 on 2022-07-11 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_finalize_message_alter_finalize_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalize',
            name='to_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 2, 23, 3, 386575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 2, 23, 3, 386575, tzinfo=utc)),
        ),
    ]
