# Generated by Django 4.0.5 on 2022-07-11 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_alter_finalize_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalize',
            name='message',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_completion_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 2, 48, 24, 249095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yojanadetails',
            name='prj_start_date_en',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 2, 48, 24, 249095, tzinfo=utc)),
        ),
    ]
